spring:
  application:
    name: Pick-Car

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false

security:
  whitelist: ${SECURITY_WHITELIST}
  jwt:
    secret-key: ${JWT_SECRET_KEY}
    expiration-time: ${JWT_EXPIRATION_TIME}