spring:
  application:
    name: Pick-Car

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_ACCOUNT}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          debug: true
          auth: true
          connection timeout: 5000
          starttls:
              enable: true

security:
  whitelist: ${SECURITY_WHITELIST}
  jwt:
    secret-key: ${JWT_SECRET_KEY}
    expiration-time: ${JWT_EXPIRATION_TIME}

swagger:
  dev-server-url: ${SWAGGER_DEV_SERVER_URL}
  local-server-url: ${SWAGGER_LOCAL_SERVER_URL}

mail:
  imap-server: ${MAIL_IMAP_SERVER}
  imap-port: ${MAIL_IMAP_PORT}
  account: ${MAIL_ACCOUNT}
  password: ${MAIL_PASSWORD}

payment:
  secret-key: ${PAYMENT_SECRET_KEY}
  base-url: ${PAYMENT_BASE_URL}
  confirm-endpoint: ${PAYMENT_CONFIRM_ENDPOINT}
  cancel-endpoint: ${PAYMENT_CANCEL_ENDPOINT}