spring:
  config:
    activate:
      on-profile: test

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

  datasource:
    url: ${TEST_DATABASE_URL}
    username: ${TEST_DATABASE_USERNAME}
    password: ${TEST_DATABASE_PASSWORD}

  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    org.hibernate.SQL: debug