name: Test Pipeline

on:
  pull_request:
    types: [ "opened", "reopened", "synchronize" ]
    branches: [ "develop" ]

permissions:
  contents: read
  actions: write
  issues: write
  pull-requests: write
  checks: write

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      DATABASE_DIALECT: ${{ secrets.DATABASE_DIALECT }}
      DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      DATABASE_USERNAME: ${{ secrets.DATABASE_USERNAME }}
      JWT_EXPIRATION_TIME: ${{ secrets.JWT_EXPIRATION_TIME }}
      JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
      MAIL_ACCOUNT: ${{ secrets.MAIL_ACCOUNT }}
      MAIL_IMAP_PORT: ${{ secrets.MAIL_IMAP_PORT }}
      MAIL_IMAP_SERVER: ${{ secrets.MAIL_IMAP_SERVER }}
      MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
      REDIS_HOST: ${{ secrets.REDIS_HOST }}
      REDIS_PORT: ${{ secrets.REDIS_PORT }}
      SECURITY_WHITELIST: ${{ secrets.SECURITY_WHITELIST }}
      SWAGGER_DEV_SERVER_URL: ${{ secrets.SWAGGER_DEV_SERVER_URL }}
      SWAGGER_LOCAL_SERVER_URL: ${{ secrets.SWAGGER_LOCAL_SERVER_URL }}
      TEST_DATABASE_PASSWORD: ${{ secrets.TEST_DATABASE_PASSWORD }}
      TEST_DATABASE_URL: ${{ secrets.TEST_DATABASE_URL }}
      TEST_DATABASE_USERNAME: ${{ secrets.TEST_DATABASE_USERNAME }}
      SPRING_PROFILES_ACTIVE: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Test with Gradle
        run: ./gradlew --info test

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: ${{ always() }}
        with:
          files: build/test-results/**/*.xml

      - name: Output test logs
        if: ${{ failure() }}
        run: cat build/reports/tests/test/index.html